### ISSUE TITLE
PlaceholderAPI

### ISSUE THREAD

**Issue by DesperoKF** [seyfahni/OnlineTime#13]
Hey, 

When i using PlaceHolder API with my Scoreboard. Its shows me Error1 

Screen: http://prntscr.com/nwtrrw 

Logs are clean. I have PlaceholderAPI on my Spigot Server. But wich Expansions i need to run this ?

**Comment by seyfahni** [comment]
What version of PlaceholderAPI du you use? (`/version PlaceholderAPI`)
My plugin is build against PlacegholderAPI version 2.10.2, if your version is older, try updating it.

Placeholders should work with just PlaceholderAPI and my Plugin installed, my Plugin should register its own expansion (called `onlinetime`).

Also, which version of Spigot do you use?

**Comment by DesperoKF** [comment]
I am using Spigot 1.12.2 and Placeholder 2.9.2. Its works now with 2.10.2 but its update to slow. i set with admin 500h, 501h and 502h 

My Scoreboard updates always in 5 secs

**Comment by seyfahni** [comment]
Do you use Bungee? If so, increase the poll interval by changing `save-interval` inside the OnlineTime config.yml to a lower value.

If not, try retrieving the value with `/papi parse me %onlinetime_string%` (instead of watching the scoreboard) and see if it updates there. If so, your scoreboard isn't reading the value every time it updates, if not, this is a bug.

**Comment by seyfahni** [comment]
@DesperoKF Did this solve your issue or is it still present?
